stages:
  - test
  - build
  - deploy
test:
  stage: test
  script: echo "Running tests"
build:
  stage: build
  script: echo "Building the app"
deploy_staging:
  stage: deploy
  script:
  - echo "Deploy to staging server"
  - mkdir .Staging
  - cp -r * .Staging
  - mv .Staging Staging
  - rsync -avze ssh ~/builds/b81cd912/0/nige/www/Staging/ root@thegreat.uk:/srv/thegreat/Staging/
  environment:
    name: staging
    url: http://www.thegreat.co.uk/Staging
  artifacts:
    paths:
    - Staging
    
  only:
  - master
deploy_prod:
  stage: deploy
  script:
  - echo "Deploy to production server"
  - mkdir .Production
  - cp -r * .Production
  - mv .Production Production
  - rsync -avz ~/builds/b81cd912/0/nige/www/Production/ root@thegreat.uk:/srv/thegreat/Production/
  environment:
    name: production
    url: https://www.thegreat.uk/Production
  artifacts:
    paths:
    - Production
  when: manual
  only:
  - master