# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
  - mkdir .Staging
  - cp -r * .Staging
  - mv .Staging Staging
  artifacts:
    paths:
    - Staging
  only:
  - Staging
  environment:
    name: staging
    url: http://www.thegreat.uk/Staging