# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: echo "Building the app"

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    pages:
  - mkdir .Staging
  - cp -r * .Staging
  - mv .Staging Staging
  artifacts:
    paths:
    - Staging
  environment:
    name: staging
    url: http://www.thegreat.uk/Staging
  only:
  - master
  

