# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
  - mkdir /srv/error.public
  - cp -r * /srv/error.public
  - mv /srv/error.public public
  artifacts:
    paths:
    - public
  only:
  - master
